name: guitarfx
channels:
  - defaults
dependencies:
  - pathlib
  - python==3.7.1
  - h5py==2.10.0
  - scipy
  - scikit-learn==0.22
  - pandas==1.3.0
  - keras==2.2.*
  - matplotlib
  - numpy==1.17.*
  - joblib
  

